server:
  port: 8088
  context-path: /student

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/stu_api?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

logging:
  level: debug

mybatis:
  mybatis.mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
  config-location: classpath:/mybatis/mybatis-config.xml
